name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.14.0 mypy==1.18.2 flakeheaven==3.3.0
      - name: Lint
        run: make lint
      - name: Check formatting
        run: make lint-format
        
